# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d28949d245677c1932eaa07356e0cd28"
name = "wishlist"
handle = "wishlist-572"
application_url = "https://dare-bench-releases-pty.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-store-wishlist.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://dare-bench-releases-pty.trycloudflare.com/auth/callback",
  "https://dare-bench-releases-pty.trycloudflare.com/auth/shopify/callback",
  "https://dare-bench-releases-pty.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
